services:
  db:
    image: mysql:8.0
    container_name: hhplus_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - hhplus_ecommerce
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql

networks:
  hhplus_ecommerce:
    driver: bridge